repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-all-unused-imports
        exclude: test/integration/(actual|expected|samples).*
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
  - repo: https://github.com/psf/blackË†c
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        exclude: test/integration/(actual|expected|samples).*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell  # See setup.cfg for args
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: test/integration/(actual|expected|samples).*
